# Generated by Django 3.2.12 on 2024-01-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='store',
            new_name='dropoff_location',
        ),
        migrations.AddField(
            model_name='car',
            name='current_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.store'),
            preserve_default=False,
        ),
    ]
