# Generated by Django 3.2.12 on 2024-01-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20240103_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='card_on_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.creditcard'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='dropoff_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
    ]
