# Generated by Django 4.2.8 on 2024-01-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_store_options_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['make', 'model']},
        ),
    ]
