# Generated by Django 3.2.12 on 2024-01-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_car_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.photo'),
            preserve_default=False,
        ),
    ]
