# Generated by Django 3.2.12 on 2024-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20240108_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.AddField(
            model_name='car',
            name='photo_url',
            field=models.CharField(default='https://s3.us-west-1.amazonaws.com/luxurylease/6ae8d0.webp', max_length=100),
            preserve_default=False,
        ),
    ]
