# Generated by Django 3.2.12 on 2024-01-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20240108_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
